### PR TITLE
Test matlab

### PR DESCRIPTION
**Pull request by viktor76525**

### CODE REVIEW

**Comment by jasonmotha** [comment]
Got an interesting error from the test - it still passed.

```test_GMM_models/test_ASK_2014_nga.py::test_ASK_2014_nga Traceback (most recent call last):

  File "/home/travis/build/ucgmsim/Empirical_Engine/empirical/test/test_GMM_models/test_matlab/ASK_2014_nga_verify.py", line 45, in <module>

    sa, sigma = ASK_2014_nga(site, fault, period=p, region=l, f_hw=h, f_as=f)

  File "/home/travis/build/ucgmsim/Empirical_Engine/empirical/GMM_models/ASK_2014_nga.py", line 205, in ASK_2014_nga

    Sa_low, sigma_low = sa_sigma(ip_low)

  File "/home/travis/build/ucgmsim/Empirical_Engine/empirical/GMM_models/ASK_2014_nga.py", line 180, in sa_sigma

    region,

  File "/home/travis/build/ucgmsim/Empirical_Engine/empirical/GMM_models/ASK_2014_nga.py", line 325, in ASK_2014_sub_1

    f4 = hanging_wall()

  File "/home/travis/build/ucgmsim/Empirical_Engine/empirical/GMM_models/ASK_2014_nga.py", line 316, in hanging_wall

    if ry0 - Ry1 <= 0:

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

PASSED```

**Comment by viktor76525** [comment]
> What's up with this test?

Ry0 was changed to Ry but not changed in comments or tests

**Comment by jasonmotha** [comment]
> > What's up with this test?
> 
> Ry0 was changed to Ry but not changed in comments or tests

Ah yep. That's an easy fix. Do you know why the test was marked as pass even though it had an error?

**Comment by viktor76525** [comment]
tests were subproccessed so they didn't pass the assertion on, fixed. note you put a change into this branch too

**Pull request merged**
